{{- if not .Values.ldap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.secretName" . }}
  labels: {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ROOT_PASSWORD: {{ required "set ldap.rootPassword or ldap.existingSecret" .Values.ldap.rootPassword | quote }}
{{- end }}
